### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by Xghayor** [the-faizmohammad/conferencePage#2]
<h3>Good work implementing all the project requirements, However, There are still some recommended changes that you may fix to enhance UX</h3>

1. The image in the footer part have to be a link that redirect to the home page and also have to be the same logo with the header logo. RD
2. As per the provided design there should be horizontal lines beneath Main and Feature speakers section. Please, Include those. AH

**Comment by the-faizmohammad** [comment]
Thanks for highlighting the issue. I will try implement the same.
